function mostrarResultado(auto) {
    // Actualizar HP y Torque en el HTML
    document.getElementById('hp-original').innerText = auto.specs.hp_orig;
    document.getElementById('hp-stage1').innerText = auto.specs.hp_stg1;
    document.getElementById('hp-stage2').innerText = auto.specs.hp_stg2 || 'N/A';
    
    // Actualizar precios de servicios extra
    document.getElementById('check-egr').dataset.price = auto.precios.egr_off;
    document.getElementById('check-dpf').dataset.price = auto.precios.dpf_off;
    
    // Si el auto no tiene DPF (ej. es bencinero), ocultar la opción
    const contenedorDPF = document.getElementById('contenedor-dpf');
    contenedorDPF.style.display = auto.precios.dpf_off > 0 ? 'flex' : 'none';

    updatePrice(); // Llamar a la función de suma que hicimos antes
}
const VEHICULOS = [
    {
        "marca": "Alfa Romeo",
        "modelo": "147",
        "año": "2001-2005",
        "motor": "2.0 TS",
        "combustible": "Bencina",
        "hp_orig": 150,
        "nm_orig": 181,
        "hp_stg1": 165,
        "nm_stg1": 200,
        "precio_st1": 200000,
        "precio_egr": 0,
        "precio_stage2": 0
    },
    {
        "marca": "Mitsubishi",
        "modelo": "ASX",
        "año": "2010-2015",
        "motor": "1.6 MIVEC",
        "combustible": "Bencina",
        "hp_orig": 115,
        "nm_orig": 154,
        "hp_stg1": 122,
        "nm_stg1": 160,
        "precio_st1": 180000,
        "precio_egr": 0,
        "precio_dpf": 0
    },
    {
        "marca": "Nissan",
        "modelo": "370z",
        "año": "2012-2015",
        "motor": "3.7 V6",
        "combustible": "Bencina",
        "hp_orig": 330,
        "nm_orig": 366,
        "hp_stg1": 350,
        "nm_stg1": 386,
        "hp_stg2": 365, 
        "nm_stg2": 406,
        "has_pops": true,
        "precio_st1": 180000,
        "precio_stg2": 250000,
        "precio_pops": 150000,
        "precio_egr": 0
    },
    {
        "marca": "Volkswagen",
        "modelo": "Amarok",
        "año": "2010-2015",
        "motor": "2.0TDI",
        "combustible": "Diésel",
        "hp_orig": 180,
        "nm_orig": 420,
        "hp_stg1": 214, 
        "nm_stg1": 500,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Audi",
        "modelo": "Q7",
        "año": "2010-2015",
        "motor": "3.0 V6 TDI",
        "combustible": "Diésel",
        "hp_orig": 272,
        "nm_orig": 600,
        "hp_stg1": 322, 
        "nm_stg1": 690,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Mercedes Benz",
        "modelo": "GLA 220D",
        "año": "2019-2021",
        "motor": "2.1D",
        "combustible": "Diésel",
        "hp_orig": 177,
        "nm_orig": 350,
        "hp_stg1": 210, 
        "nm_stg1": 420,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Mercedes Benz",
        "modelo": "A200",
        "año": "2019-2021",
        "motor": "1.6T",
        "combustible": "Bencina",
        "hp_orig": 156,
        "nm_orig": 250,
        "hp_stg1": 186, 
        "nm_stg1": 310,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Mitsubishi",
        "modelo": "L200 Katana",
        "año": "2020-2024",
        "motor": "2.4D",
        "combustible": "Diésel",
        "hp_orig": 177,
        "nm_orig": 350,
        "hp_stg1": 210, 
        "nm_stg1": 420,
        "hp_stg2": 250,
        "nm_stg2": 500,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_stg2": 2000000
    },
    {
        "marca": "Nissan",
        "modelo": "NP300",
        "año": "2020-2024",
        "motor": "2.3D",
        "combustible": "Diésel",
        "hp_orig": 160,
        "nm_orig": 403,
        "hp_stg1": 190, 
        "nm_stg1": 458,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Audi",
        "modelo": "A3",
        "año": "2010-2014",
        "motor": "1.8T",
        "combustible": "Bencina",
        "hp_orig": 160, // terminar 
        "nm_orig": 403,
        "hp_stg1": 190, 
        "nm_stg1": 458,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Ford",
        "modelo": "Ranger",
        "año": "2014-2018",
        "motor": "3.2D",
        "combustible": "Diésel",
        "hp_orig": 200, 
        "nm_orig": 470,
        "hp_stg1": 232, 
        "nm_stg1": 550,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Kia",
        "modelo": "Sorento",
        "año": "2014-2018",
        "motor": "2.2 CRDI",
        "combustible": "Diésel",
        "hp_orig": 200, 
        "nm_orig": 440,
        "hp_stg1": 232, 
        "nm_stg1": 496,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Volvo",
        "modelo": "V40",
        "año": "2014-2018",
        "motor": "D2 2.0",
        "combustible": "Diésel",
        "hp_orig": 120, 
        "nm_orig": 280,
        "hp_stg1": 170, 
        "nm_stg1": 370,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "Audi",
        "modelo": "A3",
        "año": "2010-2015",
        "motor": "1.2 TFSI",
        "combustible": "Bencina",
        "hp_orig": 105, 
        "nm_orig": 175,
        "hp_stg1": 130, 
        "nm_stg1": 225,
        "precio_st1": 180000,
        "precio_egr": 280000,
        "precio_dpf": 0
    },
    {
        "marca": "BMW",
        "modelo": "120i (F20-F21 LCI)",
        "año": "2012-2015",
        "motor": "2.0T (B48)",
        "combustible": "Bencina",
        "hp_orig": 184,
        "nm_orig": 250,
        "hp_stg1": 260,
        "nm_stg1": 400,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Audi",
        "modelo": "A6 C7",
        "año": "2011-2018",
        "motor": "3.0 TFSI",
        "combustible": "Bencina",
        "hp_orig": 300,
        "nm_orig": 440,
        "hp_stg1": 424,
        "nm_stg1": 540,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Ford",
        "modelo": "Fusion",
        "año": "2012-2015",
        "motor": "2.0T EcoBoost",
        "combustible": "Bencina",
        "hp_orig": 240,
        "nm_orig": 340,
        "hp_stg1": 285,
        "nm_stg1": 440,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Volkswagen",
        "modelo": "Amarok",
        "año": "2012-2015",
        "motor": "3.0 TDI V6",
        "combustible": "Diésel",
        "hp_orig": 224,
        "nm_orig": 500,
        "hp_stg1": 320,
        "nm_stg1": 676,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Nissan",
        "modelo": "March",
        "año": "2012-2015",
        "motor": "HR16",
        "combustible": "Bencina",
        "hp_orig": 106,
        "nm_orig": 142,
        "hp_stg1": 116,
        "nm_stg1": 152,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mitsubishi",
        "modelo": "Montero (IV)",
        "año": "2012-2015",
        "motor": "3.2D",
        "combustible": "Diésel",
        "hp_orig": 200,
        "nm_orig": 441,
        "hp_stg1": 245,
        "nm_stg1": 522,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Nissan",
        "modelo": "350z",
        "año": "2012-2015",
        "motor": "3.5 V6",
        "combustible": "Bencina",
        "hp_orig": 301,
        "nm_orig": 370,
        "hp_stg1": 311,
        "nm_stg1": 385,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Kia",
        "modelo": "Stinger",
        "año": "2012-2015",
        "motor": "3.3 V6 Twin Turbo",
        "combustible": "Bencina",
        "hp_orig": 370,
        "nm_orig": 510,
        "hp_stg1": 402,
        "nm_stg1": 608,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Nissan",
        "modelo": "350z",
        "año": "2005",
        "motor": "3.5 VQ35",
        "combustible": "Bencina",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402,
        "nm_stg1": 608,
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Kia",
        "modelo": "Seltos",
        "año": "2020-2023",
        "motor": "1.6",
        "combustible": "Bencina",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402, //sube 12 hp
        "nm_stg1": 608, //sube 15 nm
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Audi",
        "modelo": "Q5 8R Mk2",
        "año": "2012-2016",
        "motor": "1.6",
        "combustible": "Bencina",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402, //sube 45 hp
        "nm_stg1": 608, //sube 70 nm
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mitsubishi",
        "modelo": "Galant",
        "año": "1998-2003",
        "motor": "2.0 4G63",
        "combustible": "Bencina",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402, //sube 10 hp
        "nm_stg1": 608, //sube 18 nm
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Chevrolet",
        "modelo": "Camaro SS",
        "año": "2010-2016",
        "motor": "6.2 V8",
        "combustible": "Bencina",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402, //sube 20 hp
        "nm_stg1": 608, //sube 25 nm
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "BMW",
        "modelo": "M240i F2X LCI",
        "año": "2017-2021",
        "motor": "3.0 TwinPower Turbo B58",
        "combustible": "Bencina",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402, //sube 60 hp
        "nm_stg1": 608, //sube 80 nm
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Kia",
        "modelo": "Sorento",
        "año": "2024-2026",
        "motor": "3.5 V6 M14 FCL",
        "combustible": "Bencina",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402, //sube 60 hp
        "nm_stg1": 608, //sube 80 nm
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Hyundai",
        "modelo": "SantaFe",
        "año": "2018-2020",
        "motor": "2.2 CRDI",
        "combustible": "Diesel",
        "hp_orig": 370,  // arreglar
        "nm_orig": 510,
        "hp_stg1": 402, //sube 32 hp
        "nm_stg1": 608, //sube 45 nm
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Lexus",
        "modelo": "Is250",
        "año": "2008-2013",
        "motor": "2.5 V6",
        "combustible": "Bencina",
        "hp_orig": 208,  
        "nm_orig": 252,
        "hp_stg1": 220, 
        "nm_stg1": 262, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Lexus",
        "modelo": "Is200",
        "año": "2016-2020",
        "motor": "2.0T",
        "combustible": "Bencina",
        "hp_orig": 245,  
        "nm_orig": 350,
        "hp_stg1": 265, 
        "nm_stg1": 400, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Lexus",
        "modelo": "Is350",
        "año": "2013-2016",
        "motor": "3.5 V6",
        "combustible": "Bencina",
        "hp_orig": 306,  
        "nm_orig": 376,
        "hp_stg1": 321, 
        "nm_stg1": 391, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Lexus",
        "modelo": "gs300",
        "año": "2008-2011",
        "motor": "3.0 V6",
        "combustible": "Bencina",
        "hp_orig": 249,  
        "nm_orig": 310,
        "hp_stg1": 264, 
        "nm_stg1": 325, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Volvo",
        "modelo": "S60/V60",
        "año": "2015-2019",
        "motor": "2.0 T5",
        "combustible": "Bencina",
        "hp_orig": 245,  
        "nm_orig": 350,
        "hp_stg1": 265, 
        "nm_stg1": 450, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Volvo",
        "modelo": "S60/V60",
        "año": "2015-2019",
        "motor": "3.0 T6",
        "combustible": "Bencina",
        "hp_orig": 350,  
        "nm_orig": 500,
        "hp_stg1": 400, 
        "nm_stg1": 600, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Volvo",
        "modelo": "V40",
        "año": "2015-2020",
        "motor": "3.0 T6",
        "combustible": "Bencina",
        "hp_orig": 350,  
        "nm_orig": 500,
        "hp_stg1": 400, 
        "nm_stg1": 600, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mazda",
        "modelo": "3",
        "año": "2016-2019",
        "motor": "2.0 Skyactiv-G",
        "combustible": "Bencina",
        "hp_orig": 165,  
        "nm_orig": 210,
        "hp_stg1": 175, 
        "nm_stg1": 220, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Cupra",
        "modelo": "Formentor",
        "año": "2021-2023",
        "motor": "2.0 TSI",
        "combustible": "Bencina",
        "hp_orig": 190,  
        "nm_orig": 320,
        "hp_stg1": 235, 
        "nm_stg1": 400, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Cupra",
        "modelo": "Formentor",
        "año": "2021-2023",
        "motor": "2.0 TSI",
        "combustible": "Bencina",
        "hp_orig": 310,  
        "nm_orig": 400,
        "hp_stg1": 380, 
        "nm_stg1": 500, 
        "hp_stg2": 430, 
        "nm_stg2": 550,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Dodge",
        "modelo": "RAM 1500",
        "año": "2013-2019",
        "motor": "5.7 V8 HEMI",
        "combustible": "Bencina",
        "hp_orig": 390,  
        "nm_orig": 552,
        "hp_stg1": 410, 
        "nm_stg1": 590, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mercedes Benz",
        "modelo": "A200",
        "año": "2015-2018",
        "motor": "1.6 Turbo",
        "combustible": "Bencina",
        "hp_orig": 156,  
        "nm_orig": 250,
        "hp_stg1": 175, 
        "nm_stg1": 310, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mercedes Benz",
        "modelo": "A250 W176",
        "año": "2015-2018",
        "motor": "2.0 Turbo",
        "combustible": "Bencina",
        "hp_orig": 211,  
        "nm_orig": 350,
        "hp_stg1": 250, 
        "nm_stg1": 400, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mercedes Benz",
        "modelo": "A45 W176",
        "año": "2015-2018",
        "motor": "2.0 Turbo",
        "combustible": "Bencina",
        "hp_orig": 381,  
        "nm_orig": 475,
        "hp_stg1": 420, 
        "nm_stg1": 540, 
        "hp_stg2": 440, 
        "nm_stg2": 560,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mercedes Benz",
        "modelo": "GLC 43",
        "año": "2019-2023",
        "motor": "3.0 BiTurbo",
        "combustible": "Bencina",
        "hp_orig": 390,  
        "nm_orig": 520,
        "hp_stg1": 420, 
        "nm_stg1": 620, 
        "hp_stg2": 430, 
        "nm_stg2": 640,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Volvo",
        "modelo": "XC60",
        "año": "2017-2021",
        "motor": "2.0 D5",
        "combustible": "Diésel",
        "hp_orig": 235,  
        "nm_orig": 480,
        "hp_stg1": 280, 
        "nm_stg1": 540, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Volvo",
        "modelo": "XC60",
        "año": "2017-2021",
        "motor": "2.0 D4",
        "combustible": "Diésel",
        "hp_orig": 190,  
        "nm_orig": 400,
        "hp_stg1": 235, 
        "nm_stg1": 470, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Kia",
        "modelo": "Sportage",
        "año": "2016-2018",
        "motor": "2.0 CRDI",
        "combustible": "Diésel",
        "hp_orig": 184,  
        "nm_orig": 400,
        "hp_stg1": 205, 
        "nm_stg1": 450, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Hyundai",
        "modelo": "Santa Fe",
        "año": "2015-2019",
        "motor": "2.2 CRDI",
        "combustible": "Diésel",
        "hp_orig": 200,  
        "nm_orig": 440,
        "hp_stg1": 230, 
        "nm_stg1": 500, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Infinity",
        "modelo": "Q50",
        "año": "2013-2017",
        "motor": "2.0T",
        "combustible": "Bencina",
        "hp_orig": 211,  
        "nm_orig": 350,
        "hp_stg1": 250, 
        "nm_stg1": 400, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Infinity",
        "modelo": "FX37",
        "año": "2008-2013",
        "motor": "3.7 V6",
        "combustible": "Bencina",
        "hp_orig": 320,  
        "nm_orig": 360,
        "hp_stg1": 340, 
        "nm_stg1": 380, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Subaru",
        "modelo": "Outback",
        "año": "2014-2018",
        "motor": "2.0D BOXER",
        "combustible": "Diésel",
        "hp_orig": 150,  
        "nm_orig": 350,
        "hp_stg1": 180, 
        "nm_stg1": 400, 
        "hp_stg2": 0, 
        "nm_stg2": 0,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },
    {
        "marca": "Mini",
        "modelo": "Cooper F56",
        "año": "2014-2018",
        "motor": "1.5 Turbo ",
        "combustible": "Diésel",
        "hp_orig": 136,  
        "nm_orig": 220,
        "hp_stg1": 165, 
        "nm_stg1": 280, 
        "hp_stg2": 185, 
        "nm_stg2": 300,
        "has_pops": false,
        "precio_st1": 180000,
        "precio_stg2": 0,
        "precio_pops": 0,
        "precio_egr": 0
    },


];
